### ISSUE TITLE
Codebuild standard image

### ISSUE THREAD

**Issue by cavis** [PRX/Infrastructure#325]
Currently we're running on the `aws/codebuild/docker:18.09.0`.  All those specific runtime images are now unsupported, so we should switch to the standard ones.

- [x] Change codebuild to the Ubuntu Standard Image 2.0
- [x] In _all of our repos buildspec.yml_, add a runtime:
    ```yml
    install:
      runtime-versions:
        docker: 18
    ```
- [x] In Infrastructure, use a python runtime instead (and make sure it has pip)
